### PR TITLE
Port upstream Cairo 1.17.8

### PR DESCRIPTION
**Pull request by andreittr**
Files under include/ and boilerplate/ are generated by the upstream build process and adapted for Unikraft.

Depends on the following ports:
- https://github.com/unikraft/lib-pixman/pull/1
- https://github.com/unikraft/lib-libpng/pull/3
- https://github.com/unikraft/lib-freetype/pull/1

### CODE REVIEW

**Review by StefanJum — APPROVED** [review]
This works, but just on x86 (same missing header as in (`libdeflate`)[https://github.com/unikraft/lib-libdeflate/pull/1]). If it's known, I'll add the tag.

**Review by mariasfiraiala — COMMENTED** [review]
I am quite confused about the library order too, I get a different build error. Maybe share that too @andreittr?

**Comment by andreittr** [comment]
> This works, but just on x86 (same missing header as in (`libdeflate`)[https://github.com/[unikraft/lib-libdeflate/pull/1](https://github.com/unikraft/lib-libdeflate/pull/1)]). If it's known, I'll add the tag.

See the answer on libdeflate https://github.com/unikraft/lib-libdeflate/pull/1#issuecomment-1742953434, however arm intrinsics support may be dodgy.

> I am quite confused about the library order too, I get a different build error. Maybe share that too @andreittr?

Whoops, updated now https://github.com/unikraft/lib-python-pillow/pull/1.

**Review by StefanJum — APPROVED** [review]
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Review by mariasfiraiala — APPROVED** [review]
All good, thanks!

Reviewed-by: Maria Sfiraiala <maria.sfiraiala@gmail.com>

**Review by razvand — APPROVED** [review]
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request closed without merging**
